#!/bin/bash

wget -O /tmp/wahlkreisprognose.txt https://flo.uri.sh/visualisation/10450101/embed
cat /tmp/wahlkreisprognose.txt \
| grep '_Flourish_data =' \
| sed 's#.*_Flourish_data = {"data":\[##; s#},{#}\n{#g; s#\]},##; s#","#;#g;' \
| sed ' s#^{"label":"##; s#value":\["##; s#"\]}##' \
| sed 's#\([0-9]\{2,2\}\)\.\([0-9]\{2,2\}\)\.\([0-9]\{4,4\}\)#\3-\2-\1#; s#\,#.#g' \
> /tmp/wahlkreisprognose.csv
